Repository openshift/frr, pull requests merged in 2025-04, with the labels that each got.

#81 Syncmetallb 04042025
  API-DOCS.md
  Dockerfile
  Dockerfile.openshift
  Makefile
  README.md
  api/v1beta1/bgp_session_state_types.go
  api/v1beta1/zz_generated.deepcopy.go
  charts/frr-k8s/README.md
  charts/frr-k8s/charts/crds/templates/frrk8s.metallb.io_bgpsessionstates.yaml
  charts/frr-k8s/templates/controller.yaml
  charts/frr-k8s/templates/rbac.yaml
  charts/frr-k8s/templates/webhooks.yaml
  charts/frr-k8s/values.yaml
  cmd/main.go
  config/all-in-one/frr-k8s-prometheus.yaml
  config/all-in-one/frr-k8s.yaml
  config/crd/bases/frrk8s.metallb.io_bgpsessionstates.yaml
  config/crd/kustomization.yaml
  config/frr-k8s/frr-cm.yaml
  config/frr-k8s/frr-k8s.yaml
  config/rbac/role.yaml
  config/rbac/secrets_role.yaml
  config/webhook/service.yaml
  e2etests/pkg/dump/k8s.go
  e2etests/tests/bgp_session_status.go
  e2etests/tests/session.go
  frr-tools/metrics/collector/bfd.go
  frr-tools/metrics/collector/bgp.go
  frr-tools/metrics/vtysh/bfd.go
  frr-tools/metrics/vtysh/bgp.go
  frr-tools/status/controller/bgpsessionstate_controller.go
  frr-tools/status/controller/bgpsessionstate_controller_test.go
  frr-tools/status/controller/common_test.go
  frr-tools/status/exporter.go
  internal/frr/parse.go
  internal/frr/parse_test.go
  internal/webhooks/frrconfiguration_webhook.go
Labels: approved, lgtm

#87 OCPBUGS-55284: OpenShift Only: TEMPORARY: pin FRR version to known working rpm
  Dockerfile.openshift
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#88 OCPBUGS-55343: OpenShift Only: TEMPORARY: pin FRR version to known working rpm
  Dockerfile.openshift
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#89 OCPBUGS-55344: OpenShift Only: TEMPORARY: pin FRR version to known working rpm
  Dockerfile.openshift
Labels: approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
