Repository openshift/frr, pull requests merged in 2025-03, with the labels that each got.

#79 Align to upstream
  .golangci.yml
  hack/lint.sh
  internal/frr/templates/filters.tmpl
  internal/frr/templates/frr.tmpl
  internal/frr/testdata/TestMultipleNeighborsOneV4AndOneV6.golden
  internal/frr/testdata/TestMultipleNeighborsOneV4AndOneV6DisableMP.golden
  internal/frr/testdata/TestMultipleRoutersImportVRFs.golden
  internal/frr/testdata/TestMultipleRoutersMultipleNeighs.golden
  internal/frr/testdata/TestSingleSession
  internal/frr/testdata/TestSingleSession.golden
  internal/frr/testdata/TestSingleSessionBFD.golden
  internal/frr/testdata/TestSingleSessionWithAlwaysBlock.golden
  internal/frr/testdata/TestSingleSessionWithEBGPMultihop.golden
  internal/frr/testdata/TestSingleSessionWithEBGPMultihopAndExtras.golden
  internal/frr/testdata/TestSingleSessionWithExternalASN.golden
  internal/frr/testdata/TestSingleSessionWithGracefulRestart.golden
  internal/frr/testdata/TestSingleSessionWithIPv6SingleHop.golden
  internal/frr/testdata/TestSingleSessionWithInternalASN.golden
  internal/frr/testdata/TestSingleUnnumberedSession.golden
  internal/frr/testdata/TestTwoRoutersTwoNeighbors.golden
  internal/frr/testdata/TestTwoRoutersTwoNeighborsBFD.golden
  internal/frr/testdata/TestTwoSessionsAcceptAll.golden
  internal/frr/testdata/TestTwoSessionsAcceptSomeV4.golden
  internal/frr/testdata/TestTwoSessionsAcceptV4AndV6.golden
Labels: approved, lgtm

#76 OCPBUGS-48305: Use metrics for readiness/liveness probes
  charts/frr-k8s/README.md
  charts/frr-k8s/templates/controller.yaml
  charts/frr-k8s/templates/webhooks.yaml
  charts/frr-k8s/values.yaml
  cmd/main.go
  config/all-in-one/frr-k8s-prometheus.yaml
  config/all-in-one/frr-k8s.yaml
  config/default/frr-k8s_auth_proxy_patch.yaml
  config/frr-k8s/frr-k8s.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#77 OCPBUGS-44111: Use metrics for readiness/liveness probes
  charts/frr-k8s/README.md
  charts/frr-k8s/templates/controller.yaml
  charts/frr-k8s/templates/webhooks.yaml
  charts/frr-k8s/values.yaml
  cmd/main.go
  config/all-in-one/frr-k8s-prometheus.yaml
  config/all-in-one/frr-k8s.yaml
  config/default/frr-k8s_auth_proxy_patch.yaml
  config/frr-k8s/frr-k8s.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
